### PR TITLE
plugin: implementing the example with the class exstention

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
I found this pattern very cool to implement the RPC method and register it, and also this pattern may help with the annotations in the future

Build on top https://github.com/dart-lightning/lndart.clightning/pull/40

### CODE REVIEW

**Review by swaptr — DISMISSED** [review]
Really interesting approach. Lots to learn here. Thank you so much. 
ACK.

**Comment by vincenzopalazzo** [comment]
I think you ran some wrong command :) can you delete last commit that you made? :) 

 You should be able to rebase and merge if there is no conflicts with Github button! otherwise ask me and I will rebase

**Comment by swaptr** [comment]
Just rebasing on my local machine, shouldn't have used the web gui.

**Comment by vincenzopalazzo** [comment]
Reverted the merge commit, and rebase on top of the master!

Now the CI should be fine!

**Review by swaptr — APPROVED** [review]
Looks good. Thank you.

**Pull request merged**
